# WEB
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    set: app
spec:
  ports:
    - name: http
      port: 8080
  clusterIP: None
  selector:
    app: web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: $TRIPLESCALE
  template:
    metadata:
      labels:
        app: web
        set: app
    spec:
      containers:
        - name: web
          imagePullPolicy: IfNotPresent
          image: eu.gcr.io/$PROJECT_ID/motes-web:$CONTAINER_VERSION
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-canary
  labels:
    app: web-canary
    set: app
spec:
  ports:
    - name: http
      port: 8080
  clusterIP: None
  selector:
    app: web-canary
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-canary
spec:
  replicas: $TRIPLESCALE
  template:
    metadata:
      labels:
        app: web-canary
        set: app
    spec:
      containers:
        - name: web-canary
          imagePullPolicy: IfNotPresent
          image: eu.gcr.io/$PROJECT_ID/motes-web:$CONTAINER_VERSION
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"