
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: server
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        imagePullPolicy: IfNotPresent
        image: eu.gcr.io/$PROJECT_ID/motes-redis:$CONTAINER_VERSION
        ports:
        - containerPort: 6379
          name: server