pipelines:
  build:
    group: motes
    label_template: "${github[:8]}"
    locking: off
    materials:
      github:
        git: https://github.com/cilliemalan/motes.git
        branch: master
    stages:
      - checks:
          jobs:
            environment:
              tasks:
                - script: build-scripts/check-environment.sh
      - prerequisites:
          jobs:
            npm:
              tasks:
                - script: |
                    cd web
                    npm install