pipelines:
  prepare:
    group: motes
    label_template: "${github[:8]}"
    locking: off
    materials:
      github:
        git: https://github.com/cilliemalan/motes.git
        branch: master
    stages:
      - checks:
          jobs:
            environment:
              tasks:
                - script: build-scripts/check-environment.sh
      - prerequisites:
          jobs:
            npm:
              tasks:
                - script: |
                    cd web
                    echo "now in $(pwd)"
                    npm --version
                    npm install
                    echo "ran npm install"
            dev-cluster:
              tasks:
                - script: "echo Create dev cluster if needed..."
      - code-checks:
          jobs:
            lint:
              tasks:
                - script: "echo Lint..."