pipelines:
  developmentpipe:
    group: motes
    label_template: "${github[:8]}"
    locking: off
    materials:
      github:
        git: https://github.com/cilliemalan/motes.git
        branch: master
    stages:
      - prerequisites:
        jobs:
          npm:
            tasks:
              - script: cd web && npm install