pipelines:
  # the prepare pipeline will perform multiple checks on
  # the environment to prepare for the build. This pipe
  # will check the agent environment, run lints and
  # code checks, and check if the dev cluster is up
  # and running
  prepare:
    group: motes
    label_template: "${github[:8]}"
    locking: off
    materials:
      github:
        git: https://github.com/cilliemalan/motes.git
        branch: master
    stages:
      - checks:
          jobs:
            environment:
              tasks:
                - script: build-scripts/check-agent.sh
      - prerequisites:
          jobs:
            npm:
              tasks:
                - script: build-scripts/prerequisites.sh
            dev-cluster:
              tasks:
                - script: "echo Create dev cluster if needed..."
      - code-checks:
          jobs:
            lint:
              tasks:
                - script: build-scripts/lint.sh
      - check:
          jobs:
            environment:
              tasks:
                - script: pwd && ls -la
      - build-containers:
          jobs:
            environment:
              tasks:
                - script: build-scripts/docker-build-current.sh --push
      - prepare-dev-environment:
          jobs:
            environment:
              tasks:
                - script: "build-scripts/prepare-environment.sh dev"
      - deploy-dev-environment:
          jobs:
            create-cluster:
              tasks:
                - script: "build-scripts/deploy-environment.sh dev"
      - unit-tests-dev:
          jobs:
            unit-tests:
              tasks:
                - script: "build-scripts/utilities/use-environment.sh dev && build-scripts/run-unit-tests.sh"
      - e2e-tests-dev:
          jobs:
            e2e-tests:
              tasks:
                - script: "build-scripts/utilities/use-environment.sh dev && build-scripts/run-e2e-tests.sh"
      - prepare-test-environment:
          jobs:
            environment:
              tasks:
                - script: "build-scripts/prepare-environment.sh test"
      - deploy-test-environment:
          jobs:
            create-cluster:
              tasks:
                - script: "build-scripts/deploy-environment.sh test"
      - unit-tests-test:
          jobs:
            unit-tests:
              tasks:
                - script: "build-scripts/utilities/use-environment.sh test && build-scripts/run-unit-tests.sh"
      - e2e-tests-test:
          jobs:
            e2e-tests:
              tasks:
                - script: "build-scripts/utilities/use-environment.sh test && build-scripts/run-e2e-tests.sh"
      - final:
          jobs:
            notify:
              tasks:
                - script: "echo done"