pipelines:
  # the prepare pipeline will perform multiple checks on
  # the environment to prepare for the build. This pipe
  # will check the agent environment, run lints and
  # code checks, and check if the dev cluster is up
  # and running
  prepare:
    group: motes
    label_template: "${github[:8]}"
    locking: off
    materials:
      github:
        git: https://github.com/cilliemalan/motes.git
        branch: master
    stages:
      - checks:
          jobs:
            environment:
              tasks:
                - script: build-scripts/check-environment.sh
      - prerequisites:
          jobs:
            npm:
              tasks:
                - script: build-scripts/prerequisites.sh
            dev-cluster:
              tasks:
                - script: "echo Create dev cluster if needed..."
      - code-checks:
          jobs:
            lint:
              tasks:
                - script: build-scripts/lint.sh
      - final:
          jobs:
            notify:
              tasks:
                - script: "echo done"
  build:
    group: motes
    label_template: "${github[:8]}"
    locking: off
    materials:
      github:
        git: https://github.com/cilliemalan/motes.git
        branch: master
      upstream:
        pipeline: prepare
        stage: final
    stages:
      - build-containers:
          jobs:
            environment:
              tasks:
                - script: build-scripts/docker-build-current.sh --pull --push
