pipelines:
  build:
    group: motes
    label_template: "${github[:8]}"
    locking: off
    materials:
      github:
        git: https://github.com/cilliemalan/motes.git
        branch: master
    stages:
      - checks:
          jobs:
            environment:
              tasks:
                - script: |
                    echo Running on: "$(uname -a)"
                    echo Environment:
                    printenv
                    echo && echo

                    sudo -v && echo 'may sudo' || true

                    echo "Docker:"
                    docker --version
                    
                    echo "Kubectl:"
                    kubectl version

                    echo "Terraform:"
                    terraform --version

                    echo "Node:"
                    node --version
                    npm --version
      - prerequisites:
          jobs:
            npm:
              tasks:
                - script: |
                    cd web
                    npm install
      # - tests:
      #     jobs:
      #       runtests:
      #         - script: |
      #             cd web
      #             npm test