language: node_js
node_js:
  - "7"
cache: yarn

install:
  - pushd web && npm install eslint-changes && popd

script:
  #eslint
  - web/node_modules/.bin/eslint-changes
  - web/node_modules/.bin/eslint .