language: node_js
node_js:
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache: yarn

install:
  - cd web
  - npm install
  - npm install eslint-changes
  - cd ..

script:
  # eslint
  # web/node_modules/.bin/eslint-changes
  - "web/node_modules/.bin/eslint --ignore-pattern node_modules ."

  # note: we don't build docker images here because the CD system will