apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    set: ecosystem
spec:
  ports:
    - name: http
      port: 3000
  clusterIP: None
  selector:
    app: grafana
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: grafana
spec:
  serviceName: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
        set: ecosystem
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: grafana
          imagePullPolicy: IfNotPresent
          image: eu.gcr.io/$PROJECT_ID/motes-grafana:$CONTAINER_VERSION
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-config
              mountPath: /etc/grafana
          env:
            - name: GF_INSTALL_PLUGINS
              value: raintank-kubernetes-app
  volumeClaimTemplates:
    - metadata:
        name: grafana-data
        annotations:
          volume.alpha.kubernetes.io/storage-class: anything
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: grafana-config
        annotations:
          volume.alpha.kubernetes.io/storage-class: anything
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi