
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    set: ecosystem
spec:
  ports:
  - port: 9092
    name: listener
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: $SCALE
  template:
    metadata:
      labels:
        app: kafka
        set: ecosystem
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: eu.gcr.io/$PROJECT_ID/motes-kafka:$CONTAINER_VERSION
        ports:
        - containerPort: 9092
          name: listener
        volumeMounts:
        - name: kafka-logs
          mountPath: /var/lib/kafka
  volumeClaimTemplates:
  - metadata:
      name: kafka-logs
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: $DATADISKSIZE